
language: node_js
node_js:
  - "8"
before_script:
  - "npm install"

script:
  - "npm run cover"
  - "npm run check-coverage"
  - "npm run coveralls"
cache:
  directories:
    - node_modules
notifications:
  email: false
